[package]
name = "httpTest"
version = "0.1.0"
authors = ["niels"]

[dependencies]
hyper = "0.11"
hyper-tls = "0.1.3"
tokio-core = "0.1"
futures = "0.1"
serde_json = "1.0.13"
serde = "1.0.34"
serde_derive = "1.0.34"
tokio-curl = "0.1"
curl = "0.4.11"
env_logger = "0.5.6"
